name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        default: 'pypi'
        type: choice
        options:
        - pypi
        - test-pypi

jobs:
  test-pypi:
    name: "Test publish to TestPyPI"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.environment == 'test-pypi'
    environment: 
      name: test-pypi
      url: https://test.pypi.org/p/dll-scanner
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U build

    - name: Build package
      run: python -m build

    - name: Check package
      run: python -m twine check dist/*

    - name: Check if version already exists on TestPyPI
      id: version-check
      run: |
        PKG_NAME="dll-scanner"
        VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
        REPO_URL="https://test.pypi.org/simple/"
        
        echo "Checking if $PKG_NAME==$VERSION exists on TestPyPI"
        if python -m pip install --index-url $REPO_URL --dry-run "$PKG_NAME==$VERSION" 2>/dev/null; then
          echo "Version $VERSION already exists on TestPyPI"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Version $VERSION does not exist on TestPyPI, proceeding with upload"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Mint OIDC token for TestPyPI
      id: mint-token
      if: steps.version-check.outputs.exists == 'false'
      run: |
        # retrieve the ambient OIDC token
        resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=testpypi")
        oidc_token=$(echo "$resp" | jq -r '.value')
        echo "oidc-token=$oidc_token" >> $GITHUB_OUTPUT

    - name: Publish to TestPyPI
      if: steps.version-check.outputs.exists == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        attestations: true

  pypi:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'pypi')
    environment: 
      name: pypi
      url: https://pypi.org/p/dll-scanner
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U build

    - name: Build package
      run: python -m build

    - name: Check package
      run: python -m twine check dist/*

    - name: Check if version already exists on PyPI
      id: version-check
      run: |
        PKG_NAME="dll-scanner"
        VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
        REPO_URL="https://pypi.org/simple/"
        
        echo "Checking if $PKG_NAME==$VERSION exists on PyPI"
        if python -m pip install --index-url $REPO_URL --dry-run "$PKG_NAME==$VERSION" 2>/dev/null; then
          echo "Version $VERSION already exists on PyPI"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Version $VERSION does not exist on PyPI, proceeding with upload"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Mint OIDC token for PyPI
      id: mint-token
      if: steps.version-check.outputs.exists == 'false'
      run: |
        # retrieve the ambient OIDC token
        resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=pypi")
        oidc_token=$(echo "$resp" | jq -r '.value')
        echo "oidc-token=$oidc_token" >> $GITHUB_OUTPUT

    - name: Publish to PyPI
      if: steps.version-check.outputs.exists == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: true